services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: bank_db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - spring-demo
    restart: unless-stopped

  myApp:
    container_name: spring-boot
    image: spring/bootcamp
    ports:
      - "8080:8087"
    networks:
      - spring-demo
    depends_on:
      - postgres

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
