name: Bootcamp CI/CD

on:
  push:
    branches:
      - main

jobs:
  ci-cd:
    name: Build and Deploy Spring boot API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Compile
        run: mvn clean compile

      - name: Unit tests
        run: mvn clean test


